config/routes.rb
Rails.application.routes.draw do
  get 'comments/create'
  resources :rooms
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "rooms#index"
  post "/comments" => "comments#create"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :room
  belongs_to :user
end

app/models/room.rb
class Room < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    uuid = UUID.new
    file_name = params[:image].present? ? uuid.generate : ""
    if params[:image].present?
      client = Aws::S3::Client.new(region: "ap-northeast-1")
      client.put_object(
        bucket: "rails-ebs-template",
        key: file_name, body:
        params[:image].read
      )
    end
    
    if params[:content].present? || file_name
      Comment.create(
        user_id: params[:user_id].to_i,
        room_id: params[:room_id].to_i,
        content: params[:content],
        imageurl: file_name
      )
    end

    

    return redirect_to controller: 'rooms', action: 'show', id: params[:room_id].to_i
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!
  def index
    
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_room, only: [:show, :edit, :update, :destroy]

  # GET /rooms
  # GET /rooms.json
  def index
    @rooms = Room.all
  end

  # GET /rooms/1
  # GET /rooms/1.json
  def show
    @comment = Comment.new
    @comments = Comment.where(room_id: params[:id])
  end

  # GET /rooms/new
  def new
    @room = Room.new
  end

  # GET /rooms/1/edit
  def edit
  end

  # POST /rooms
  # POST /rooms.json
  def create
    @room = Room.new(room_params)

    respond_to do |format|
      if @room.save
        format.html { redirect_to @room, notice: 'Room was successfully created.' }
        format.json { render :show, status: :created, location: @room }
      else
        format.html { render :new }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rooms/1
  # PATCH/PUT /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to @room, notice: 'Room was successfully updated.' }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1
  # DELETE /rooms/1.json
  def destroy
    @room.destroy
    respond_to do |format|
      format.html { redirect_to rooms_url, notice: 'Room was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def room_params
      params.require(:room).permit(:title, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/home/index.html.erb
Rails EBS Template

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsRbsTemplate</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <a class="navbar-brand" href="/rooms" disabled >Rails EBS Template</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample05" aria-controls="navbarsExample05" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarsExample05">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="/rooms">Home</a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="/rooms/new">Create New Room</a>
          </li>
        </ul>
        <%= link_to('Logout', destroy_user_session_path, method: :delete, class: "nav-link", style: "color: white;") %>
      </div>
    </nav>
    <div class="container mx-auto" >
      <p class="notice text-center"><%= notice %></p>
      <p class="alert text-center"><%= alert %></p>
      <%= yield %>
    </div>
    

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

app/views/rooms/_form.html.erb
<%= form_with(model: room, local: true, html: {style: "
  width: 100%;
  max-width: 420px;
  padding: 15px;
  margin: auto;
"}) do |form| %>
  <% if room.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(room.errors.count, "error") %> prohibited this room from being saved:</h2>

      <ul>
      <% room.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="form-label-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: "form-control" %>
  </div>

  <div class="form-label-group">
    <%= form.label :description %>
    <%= form.text_area :description, class: "form-control" %>
  </div>
  <br />

  <div class="actions">
    <%= form.submit class: "btn btn-lg btn-primary btn-block"%>
  </div>
<% end %>

app/views/rooms/edit.html.erb
<h1 class="text-center">Editing Room</h1>

<%= render 'form', room: @room %>

<div class="text-center">
  <%= link_to 'Show', @room %> |
  <%= link_to 'Back', rooms_path %>
</div>

app/views/rooms/index.html.erb
<h1>Rooms</h1>

<div class="row">
  <% @rooms.each do |room| %>
      <div class="col-4">
        <div class="card m-2">
          <div class="card-body">
            <h5 class="card-title"><%= room.title %></h5>
            <p class="card-text"><%= room.description %></p>
            <%= link_to 'Show', room %>
          </div>
        </div>
      </div>
  <% end %>
</div>

app/views/rooms/new.html.erb
<h1 class="text-center">New Room</h1>

<%= render 'form', room: @room %>

<div class="text-center">
  <%= link_to 'Back', rooms_path %>
</div>

app/views/rooms/show.html.erb
<!-- <p>
  <strong>Title:</strong>
  <%= @room.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @room.description %>
</p> -->
<% @comments.each do | comment |  %>
  <div class="mb-5">
      <% if comment.imageurl != "" %>
        <div class="mb-2" style="
          height: 300px;
          width: 300px;
        ">
          <img src="<%= 'https://s3-ap-northeast-1.amazonaws.com/rails-ebs-template/' + comment.imageurl%>" alt="..." style="
            height: 300px;
            width: 300px;
          "/>
        </div>
      <% end %>
      <% if comment.content.present? %>
        <div class="card mb-2" style="width: 100%;">
          <div class="card-body">
            <p class="card-text"><%= comment.content %></p>
          </div>
        </div>
      <% end %>
      <small>written by user <%= comment.user.id %> / <%= comment.created_at  %> </small>
  </div>
<% end %>

<%= link_to 'Edit', edit_room_path(@room) %> |
<%= link_to 'Back', rooms_path %>

<%= form_tag "/comments", :name => "commentNew", :multipart => true do %>
  <input type="hidden" name="room_id" value="<%= @room.id %>">
  <input type="hidden" name="user_id" value="<%= current_user.id %>">
  <div class="form-group">
    <label for="exampleInputEmail1">New Comment</label>
    <textarea name="content" class="form-control" rows="3"></textarea>
  </div>
  <input type="file" name="image" accept="image/png, image/jpeg">

  <button type="submit" class="btn btn-primary">Submit</button>
<% end %>